[package]
name = "memequeue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.148"
once_cell = "1.18.0"
rand = "0.8.5"

[dev-dependencies]
proptest = "1.2.0"
tempfile = "3.8.0"
